<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MalaBars.Domain\MalaBars.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Users\ANEES RAHMAN\source\repos\MalaBarsBackend\MalaBars.Application\DTO%27s\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\ANEES RAHMAN\source\repos\MalaBarsBackend\MalaBars.Application\DTO's\.editorconfig" />
  </ItemGroup>

</Project>
